### PR TITLE
Copy the license from RequestPolicyContinued

### PR DESCRIPTION
**Pull request by fmarier**
Are the lists licensed under the same terms as RequestPolicy itself?

The repo currently doesn't say anything about the copyright of the subscriptions.

### CODE REVIEW

**Comment by nodiscc** [comment]
@fmarier Thanks for pointing this out. I don't know if subscriptions lists can reasonably be licensed under GPL (this is not really software, but user contributed lists). Maybe the [CreativeCommons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/) license would be more appropriate?

Your input is welcome @myrdd @reqsub @squarefractal

**Comment by myrdd** [comment]
From what I know it would be uncommon to use GPL. What's the license of other such lists?

I think we should choose the licence carefully. I could imagine that *license compatibility* with the licenses of other such lists might be an important aspect.

**Comment by fmarier** [comment]
The Disconnect.me list is also GPLv3+: https://services.disconnect.me/disconnect-plaintext.json

**Comment by myrdd** [comment]
Thanks for pointing that out. Is there anything that would argue agains GPL?

ABP filter list "easylist" seems not to have a license. https://adblockplus.org/de/subscriptions

**Comment by squarefractal** [comment]
>ABP filter list "easylist" seems not to have a license. https://adblockplus.org/de/subscriptions

Actually it's also GPLv3+ or CC-BY-SA 3.0:
`https://easylist-downloads.adblockplus.org/easylist.txt`:

> ! Licence: https://easylist-downloads.adblockplus.org/COPYING

>  Unless otherwise noted, the contents of the EasyList repository
(https://hg.adblockplus.org/easylist/) is dual licensed under the GNU
General Public License version 3 of the License, or (at your option)
any later version, and Creative Commons Attribution-ShareAlike 3.0
Unported, or (at your option) any later version.

It might be best to use this license.

**Comment by myrdd** [comment]
Thanks @squarefractal, dual licensing sounds like it's more flexible.

**Comment by fmarier** [comment]
I've revised this PR to include both CC BY-SA and the GPL.

**Comment by nodiscc** [comment]
Thanks

**Pull request merged**
