### PR TITLE
update deny_trackers.json

### PR DESCRIPTION
**Pull request by nodiscc**
List items copied from Peter Lowe's Ad server list at http://pgl.yoyo.org/adservers/, which is an ad server list used by default by [µBlock](https://github.com/gorhill/uBlock)

Since this is a large change, I'm submitting it as a pull request for discussion. I used the list in adblock format as a base: http://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblock&showintro=1&startdate[day]=&startdate[month]=&startdate[year]=&mimetype=plaintext This is related to  https://github.com/RequestPolicyContinued/requestpolicy/issues/14 (allow import of blacklisted items from other blacklisting extensions)

I'm wondering if this overlaps with adblock functionality.

### CODE REVIEW

**Comment by myrdd** [comment]
Great! I'd say we should try it out. The file itself is 100kB in size, that shoudn't be a problem neither when downloading nor for storage. If performance of RP drops significantly we might want to revert that change. What do you think @nodiscc?

**Comment by nodiscc** [comment]
Ok, I'll merge this and see how it goes.

**Comment by nodiscc** [comment]
By the way @myrdd this currently has no effects for users that have _Block_ as their _Default policy_, as the deny_trackers subscription is not loaded when in _block_ default policy. I think this was reported in another issue. I still have to manually blacklist those domains with my current setup.

Can you have a look?

**Comment by myrdd** [comment]
Hey @nodiscc sorry that there haven't been any changes to the main dev branch for a while now. Currently https://github.com/RequestPolicyContinued/requestpolicy/issues/489 gets my whole attention. I could work on other issues as well, but I prefer to finish e10s support first. Merging new features from `dev-1.0` to `dev-restartless-and-e10s` would be quite some work as the diffierence is already big. This is the reason why I avoided to work on `dev-1.0`.

**Pull request merged**
