### PR TITLE
allow_sameorg.json: add domains

### PR DESCRIPTION
**Pull request by CarelessChaser**
Owner TV company "Lux" (Ukraine): 24tv.ua, luxnet.ua
Owner "PrivatBank" (Ukrainian bank): privatbank.ua, privat24.ua
Owner "Tech Media" (Russia): geektimes.ru, habracdn.net, habrahabr.ru, habrastorage.org, hsto.org, megamozg.ru, moikrug.ru, tmfeed.ru, toster.ru

### CODE REVIEW

**Comment by CarelessChaser** [comment]
Hi. Is it too hard to review?

**Comment by nodiscc** [comment]
It looks ok. Please update the allow_sameorg serials (see https://github.com/RequestPolicyContinued/subscriptions/commit/c51a212f80eeaae8a70951e8ccb57f714adfe808 for an example, format is YYYYMMDD01) so I can proceed to merge

**Comment by CarelessChaser** [comment]
Updated.

**Comment by nodiscc** [comment]
The serial for `allow_sameorg` also needs to be updated to `2015120401` in `official.json`

**Comment by CarelessChaser** [comment]
Done.

**Comment by nodiscc** [comment]
:clap:

I've also added your patch to the doc as an example of a good patch https://github.com/RequestPolicyContinued/subscriptions/commit/26ab05161eac95f7cfaae70b81a058bb05587f0a, thanks for the help.

**Pull request merged**
