### PR TITLE
Added a few domains.

### PR DESCRIPTION
**Pull request by squarefractal**
A few advertising/tracking domains noted via www.howtogeek.com but in no way specific to them.

### CODE REVIEW

**Comment by squarefractal** [comment]
Any particular reason for holding this back?

**Comment by myrdd** [comment]
@nodiscc self-assigned himself, but he might not have time atm. I suppose your PR is ok.

**Comment by nodiscc** [comment]
@squarefractal Sorry for taking so long, I don't have much time these days. It's ok to add this, but you also have to update the serials in `official.json` and `official-deny_trackers.json`, see https://github.com/RequestPolicyContinued/subscriptions/commit/60319346414174222e4d210045c8c8890f26bbec

**Comment by squarefractal** [comment]
>It's ok to add this, but you also have to update the serials in official.json and official-deny_trackers.json

Done.
But I still think that its your responsibility to update these.

**Comment by nodiscc** [comment]
>  But I still think that its your responsibility to update these.

Yes I'm looking for ways to ease maintenance of this repo (rule creation, subscription updates...). A Makefile was proposed to run tests on subscription lists (https://github.com/RequestPolicyContinued/subscriptions/issues/14) but I'm still unsure it's the way to go. What tool would help contributors? Also check https://github.com/RequestPolicyContinued/subscriptions/issues/7

Thanks again @squarefractal

**Comment by myrdd** [comment]
If I understand correctly, you want a tool that works as follows:

 - you give the tool a link to a pull request, and by that you say *„the changes in this pull request are ok“*
 - the tool the automatically …
   - fetches the pull request
   - do check – e.g. whether the json is correct
   - updates the serials and commits them
   - merges the branch into the main branch
   - pushes the changes

Whether you implement such a tool using a makefile or other technology is up to you.

**Comment by squarefractal** [comment]
>you give the tool a link to a pull request, and by that you say „the changes in this pull request are ok“

You want continuous integration. Travis-CI can do those things, however it does not pull automatically.
IMO all pulls _should_ be done manually. A malicious actor can open a syntactically valid PR that passes all tests, but you wouldn't want to pull in their changes.

BTW, if the changes are acceptable, please make a pull. Thanks.

**Comment by myrdd** [comment]
You are right, @nodiscc gave his ok to this PR. I've merged it.

> it does not pull automatically

Don't you mean *push*? That would make sense to me. Nothing on the main branch should change automatically, there should always be a review.

**Comment by squarefractal** [comment]
@myrdd actually "merging of PRs" was what I was referring to :P

**Comment by nodiscc** [comment]
I want a tool like
```
$ review https://github.com/RequestPolicyContinued/subscriptions/pull/22
[info] fetching pull request...
[info] checking json validity...
[info] checking for duplicate rules...
[info] this pull request adds 2 commits and the following rules:
+      {"d":{"h":"*.bttrack.com"}},
+      {"d":{"h":"*.servebom.com"}},
+      {"d":{"h":"*.bkrtx.com"}},
+      {"d":{"h":"*.sonobi.com"}},
+      {"d":{"h":"*.springserve.com"}},
+      {"d":{"h":"*.taboola.com"}}
+      {"d":{"h":"*.ml314.com"}}
+      {"d":{"h":"*.pointclicktrack.com"}}
+      {"d":{"h":"*.optimizely.com"}}
[question] open destinations domains in browser tabs? [Y/n]
[question] open destination domain reputation info on mywot.com? [Y/n]
[question] do you want to accept this pull request? [Y/n]
[info] updating serials...
[info] squashing pull request on top of master...
[info] merging to master
[done]
```

So, not exactly continuous integration. It needs to help with manual review. This is the easy part. What is not straightforward is helping users to provide their own rules for the subscriptions, in an easy way. I use manual text replacement to beautify my user.json, then use [meld](http://meldmerge.org/) to manually merge it with a subscription, but this is clearly not optimal.

Anyway thx to you both

**Comment by nodiscc** [comment]
Caution the merge added invalid json, fixed in https://github.com/RequestPolicyContinued/subscriptions/commit/5fb94afd6a49d79ad1e8980360c0e688e3458f5b. One more reason to provide automatic maintenance tools :)

**Comment by myrdd** [comment]
Ok, it's time to create a new issue with your wish @nodiscc, don't you think?

Sorry @nodiscc for not checking, and thanks for fixing it that quickly! I can see that the new entries are not ordered alphabetically like the other entries though. You want to have that changed?

**Comment by nodiscc** [comment]
>  I can see that the new entries are not ordered alphabetically like the other entries though. You want to have that changed?

Yes, added to the list and moved to #14

**Pull request merged**
