### PR TITLE
Add heise.de, a major German IT/news portal

### PR DESCRIPTION
**Pull request by genodeftest**

### CODE REVIEW

**Comment by nodiscc** [comment]
Thanks, this will be part of the next update (I'm waiting for more rules to add; note that your PR misses updating the serial numbers as explained in the readme; I'll take care of it)

**Comment by nodiscc** [comment]
Added as part of 60319346414174222e4d210045c8c8890f26bbec. Thanks

**Comment by genodeftest** [comment]
Thanks!
Besides isn't there an easier way to run some bash scripts before submitting a new URL?

**Comment by nodiscc** [comment]
@genodeftest what would help? The easiest way to add new rules I found is to do a selective merge of your `user.json` file with `official-*.json` files in this repo. What more could we do with shell scripts?

**Pull request closed without merging**
